client localhost {
  ipaddr = 127.0.0.1
  secret = SkynityRadius
  require_message_authenticator = yes
}

client docker_network {
  ipaddr = 172.16.0.0/12
  secret = SkynityRadius
  require_message_authenticator = yes
}

client wireguard_network {
  ipaddr = 10.8.0.0/24
  secret = SkynityRadius
  require_message_authenticator = yes
}
