sql {
  dialect = "postgresql"
  driver = "rlm_sql_postgresql"

  server = "$ENV{POSTGRES_HOST}"
  port = 5432
  login = "$ENV{POSTGRES_USER}"
  password = "$ENV{POSTGRES_PASSWORD}"
  radius_db = "$ENV{POSTGRES_DB}"

  acct_table1 = "radacct"
  acct_table2 = "radacct"
  postauth_table = "radpostauth"
  authcheck_table = "radcheck"
  groupcheck_table = "radgroupcheck"
  authreply_table = "radreply"
  groupreply_table = "radgroupreply"
  usergroup_table = "radusergroup"
  delete_stale_sessions = yes
  read_groups = yes
  client_table = "nas"
  group_attribute = "SQL-Group"

  pool {
    start = 5
    min = 3
    max = 10
    spare = 3
    uses = 0
    retry_delay = 30
    lifetime = 0
    idle_timeout = 60
  }

  $INCLUDE ${modconfdir}/${.:name}/main/${dialect}/queries.conf
}
